Here I list all issues, bugs, errors and other issues.

- AssertionError: git0802
    **Error Details:**

    ```
        Following git0802 back...
        Traceback (most recent call last):
        File "D:\Desktop\github-follower\follow_back.py", line 23, in <module>
        user.add_to_following(follower)
        File "D:\Desktop\github-follower\.venv\Lib\site-packages\github\AuthenticatedUser.py", line 387, in     add_to_following
        assert isinstance(following, github.NamedUser.NamedUser), following
        AssertionError: git0802
    ```

    